// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glgknpflwgmorcgogyyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZ2tucGZsd2dtb3JjZ29neXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwNzIwODAsImV4cCI6MjA3NzY0ODA4MH0.UD23S3_o1r6YFHUpUpVueEKqJ5pE2jJo4mqn-j2yiAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});